# Generated by Django 4.0.4 on 2022-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffData',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('last_updt', models.DateTimeField()),
                ('last_updt_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'staff_data_tbl',
            },
        ),
    ]
