# Generated by Django 4.0.4 on 2022-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdata',
            name='last_updt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='last_updt_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
