# Generated by Django 4.0.4 on 2022-04-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telework', '0002_alter_staffdata_last_updt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='telework.staffdata')),
            ],
            options={
                'db_table': 'staff_ac_tbl',
            },
        ),
    ]
